name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build N push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DkrHub_USERNAME }}
          password: ${{ secrets.DkrHub_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}

      # - name: Running and Deploying with SSH to Production
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     script: |
      #       docker login -u ${{ secrets.DkrHub_USERNAME }} -p ${{ secrets.DkrHub_PASSWORD }}
      #       docker rm -f gonzu-web
      #       docker run -d --rm -p 3000:3000 --name gonzu-web ${{ github.repository }}:${{ github.sha }}
